<?php

namespace Proxies\__CG__\AgiBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Site extends \AgiBundle\Entity\Site implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'id', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'nomSite', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'etat', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'heureOuvJour', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'heureFermJour', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'heureOuvNuit', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'heureFermNuit', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'contrats', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'vacations', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'operations'];
        }

        return ['__isInitialized__', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'id', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'nomSite', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'etat', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'heureOuvJour', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'heureFermJour', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'heureOuvNuit', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'heureFermNuit', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'contrats', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'vacations', '' . "\0" . 'AgiBundle\\Entity\\Site' . "\0" . 'operations'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Site $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomSite($nomSite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomSite', [$nomSite]);

        return parent::setNomSite($nomSite);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomSite', []);

        return parent::getNomSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureOuvJour($heureOuvJour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureOuvJour', [$heureOuvJour]);

        return parent::setHeureOuvJour($heureOuvJour);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureOuvJour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureOuvJour', []);

        return parent::getHeureOuvJour();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureFermJour($heureFermJour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureFermJour', [$heureFermJour]);

        return parent::setHeureFermJour($heureFermJour);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureFermJour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureFermJour', []);

        return parent::getHeureFermJour();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureOuvNuit($heureOuvNuit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureOuvNuit', [$heureOuvNuit]);

        return parent::setHeureOuvNuit($heureOuvNuit);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureOuvNuit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureOuvNuit', []);

        return parent::getHeureOuvNuit();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureFermNuit($heureFermNuit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureFermNuit', [$heureFermNuit]);

        return parent::setHeureFermNuit($heureFermNuit);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureFermNuit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureFermNuit', []);

        return parent::getHeureFermNuit();
    }

    /**
     * {@inheritDoc}
     */
    public function addContrat(\AgiBundle\Entity\ContratSite $contrat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContrat', [$contrat]);

        return parent::addContrat($contrat);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContrat(\AgiBundle\Entity\ContratSite $contrat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContrat', [$contrat]);

        return parent::removeContrat($contrat);
    }

    /**
     * {@inheritDoc}
     */
    public function getContrats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContrats', []);

        return parent::getContrats();
    }

    /**
     * {@inheritDoc}
     */
    public function addVacation(\AgiBundle\Entity\Vacation $vacation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVacation', [$vacation]);

        return parent::addVacation($vacation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVacation(\AgiBundle\Entity\Vacation $vacation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVacation', [$vacation]);

        return parent::removeVacation($vacation);
    }

    /**
     * {@inheritDoc}
     */
    public function getVacations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVacations', []);

        return parent::getVacations();
    }

    /**
     * {@inheritDoc}
     */
    public function addOperation(\AgiBundle\Entity\Operation $operation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOperation', [$operation]);

        return parent::addOperation($operation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOperation(\AgiBundle\Entity\Operation $operation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOperation', [$operation]);

        return parent::removeOperation($operation);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperations', []);

        return parent::getOperations();
    }

}
