agi_index:
    path:     /
    defaults: { _controller: AgiBundle:Login:login }

agi_login:
    path:     /login
    defaults: { _controller: AgiBundle:Login:login }

agi_logout:
    path:     /logout
    defaults: { _controller: AgiBundle:Login:logout }

agi_homepage:
    path:     /home
    defaults: { _controller: AgiBundle:Agi:index }

ajouter_agent:
    path:     /agent
    defaults: { _controller: AgiBundle:Agent:ajouter }

modifier_agent:
    path:     /agent/edit/{id}
    defaults: { _controller: AgiBundle:Agent:modifier }

supprimer_agent:
    path:     /agent/delete/{id}
    defaults: { _controller: AgiBundle:Agent:supprimer }

liste_agent_actif:
    path:     /agents/actif
    defaults: { _controller: AgiBundle:Agent:listerActif }

liste_agent_supprime:
    path:     /agents/delete
    defaults: { _controller: AgiBundle:Agent:listerSupprime }

planning_agent:
    path:     /agent/planning/{id}
    defaults: { _controller: AgiBundle:Agent:planning }

afficher_planning_agent:
    path:     /agent/display_planning/{id}
    defaults: { _controller: AgiBundle:Agent:displayPlanning }

imprimer_planning_agent:
    path:     /agent/imprimer_planning/{id}
    defaults: { _controller: AgiBundle:Agent:imprimer }

operation_enregistrement_agent:
    path:     /agent/details/{id}
    defaults: { _controller: AgiBundle:Agent:details }

ajouter_site:
    path:     /site
    defaults: { _controller: AgiBundle:Site:ajouter }

modifier_site:
    path:     /site/edit/{id}
    defaults: { _controller: AgiBundle:Site:modifier }

supprimer_site:
    path:     /site/delete/{id}
    defaults: { _controller: AgiBundle:Site:supprimer }

planning_site:
    path:     /site/planning/{id}
    defaults: { _controller: AgiBundle:Site:planning }

afficher_planning_site:
    path:     /site/display_planning/{id}
    defaults: { _controller: AgiBundle:Site:displayPlanning }

imprimer_planning_site:
    path:     /site/imprimer_planning/{id}
    defaults: { _controller: AgiBundle:Site:imprimer }

calendrier_site:
    path:     /site/calendrier/{id}
    defaults: { _controller: AgiBundle:Site:calendrier }

afficher_calendrier_site:
    path:     /site/display_calendrier/{id}
    defaults: { _controller: AgiBundle:Site:displayCalendrier }

liste_site_actif:
    path:     /sites/actif
    defaults: { _controller: AgiBundle:Site:listerActif }

liste_site_supprime:
    path:     /sites/delete
    defaults: { _controller: AgiBundle:Site:listerSupprime }

operation_enregistrement_site:
    path:     /site/details/{id}
    defaults: { _controller: AgiBundle:Site:details }

site_enregistrer_vacation:
    path:     /site/save/vacation/{id}
    defaults: { _controller: AgiBundle:Vacation:enregistrer }

site_modifier_vacation:
    path:     /vacation/edit/{id}
    defaults: { _controller: AgiBundle:Vacation:modifier }

site_supprimer_vacation:
    path:     /vacation/delete/{id}
    defaults: { _controller: AgiBundle:Vacation:supprimer }

liste_sites_vacations_actives:
    path:     /sites/vacations/actives
    defaults: { _controller: AgiBundle:Vacation:listerActif }

liste_sites_vacations_supprimes:
    path:     /sites/vacations/supprimes
    defaults: { _controller: AgiBundle:Vacation:listerSupprime }

site_recapitulatif:
    path:     /site/recapitulatif/{id}
    defaults: { _controller: AgiBundle:Site:recapitulatif }

agent_recapitulatif:
    path:     /agent/recapitulatif/{id}
    defaults: { _controller: AgiBundle:Agent:recapitulatif }

configurer_heure:
    path:     /config_heure
    defaults: { _controller: AgiBundle:HeurePanier:configurerHeure }

modifier_config_heure:
    path:     /config_heure/edit/{id}
    defaults: { _controller: AgiBundle:HeurePanier:modifierHeure }
