services:
    sumheure:
      class: AgiBundle\Twig\Extension\SumHeureExtension
      tags:
        - { name: twig.extension }

    dayByDate:
      class: AgiBundle\Twig\Extension\DayByDateExtension
      tags:
        - { name: twig.extension }

    formaterChaine:
          class: AgiBundle\Twig\Extension\FormaterChaineExtension
          tags:
            - { name: twig.extension }

    app.html2pdf:
      class: AgiBundle\Service\CustomHtml2Pdf