services:
    sumheure:
      class: AgiBundle\Twig\Extension\SumHeureExtension
      tags:
        - { name: twig.extension }

    twig.extension.intl:
      class: Twig_Extensions_Extension_Intl
      tags:
        - { name: twig.extension }

    app.html2pdf:
      class: AgiBundle\Service\CustomHtml2Pdf