services:
    app.form.registration:
        class: AgiBundle\Form\RegistrationType
        tags:
          - { name: form.type, alias: app_user_registration }

    sumheure:
      class: AgiBundle\Twig\Extension\SumHeureExtension
      tags:
        - { name: twig.extension }

    dayByDate:
      class: AgiBundle\Twig\Extension\DayByDateExtension
      tags:
        - { name: twig.extension }

    formaterChaine:
          class: AgiBundle\Twig\Extension\FormaterChaineExtension
          tags:
            - { name: twig.extension }

    app.html2pdf:
      class: AgiBundle\Service\CustomHtml2Pdf