<?php

namespace AgiBundle\Repository;

/**
 * AgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNbAgents($etat){

        $qb = $this->createQueryBuilder('a');
        $qb->select('COUNT(a)')
            ->where('a.etat = :etat')
            ->setParameter('etat', $etat);

        $query = $qb->getQuery();

        return $query->getSingleScalarResult();

    }

    public function findAgents($etat){

        $qb = $this->createQueryBuilder('a');
        $qb->select('a')
            ->where('a.etat = :etat')
            ->setParameter('etat', $etat)
            ->orderBy('a.nom', 'ASC');

        $query = $qb->getQuery();

        return $query->getResult();

    }

    public function findAgentByName($name){

        $qb = $this->createQueryBuilder('a');
        $qb->select('a')
            ->where('a.nom LIKE :nom')
            ->setParameter('nom', '%'.$name.'%');

        $query = $qb->getQuery();///A enlever ou pas

        return $query->getResult();

    }

}
