<?php

namespace AgiBundle\Repository;

/**
 * ContratAgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratAgentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findContratsAgents($etat){

        $qb = $this->createQueryBuilder('c');
        $qb->select('c')
            ->join('c.agent', 'a')
            ->where('c.etat = :etat')
            ->setParameter('etat', $etat)
            ->orderBy('a.nom', 'ASC');

        $query = $qb->getQuery();

        return $query->getResult();

    }
}
