<?php

namespace AgiBundle\Repository;

/**
 * ContratSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratSiteRepository extends \Doctrine\ORM\EntityRepository
{
}
