<?php

namespace AgiBundle\Repository;

/**
 * HeurePanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeurePanierRepository extends \Doctrine\ORM\EntityRepository
{
}
