<?php

namespace AgiBundle\Repository;

/**
 * OperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAgentOperations($id){

        $qb = $this->createQueryBuilder('o');
        $qb->select('o')
            ->where('o.agent = :id')
            ->setParameter('id', $id);

        $query = $qb->getQuery();

        return $query->getResult();

    }

    public function findSitesOperations($id){

        $qb = $this->createQueryBuilder('o');
        $qb->select('o')
            ->where('o.site = :id')
            ->setParameter('id', $id);

        $query = $qb->getQuery();

        return $query->getResult();

    }


}
