<?php

namespace AgiBundle\Repository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNbSites($etat){

        $qb = $this->createQueryBuilder('s');
        $qb->select('COUNT(s)')
            ->where('s.etat = :etat')
            ->setParameter('etat', $etat);

        $query = $qb->getQuery();

        return $query->getSingleScalarResult();
    }

    public function findSites($etat){

        $qb = $this->createQueryBuilder('s');
        $qb->select('s')
            ->where('s.etat = :etat')
            ->setParameter('etat', $etat)
            ->orderBy('s.nomSite', 'ASC');

        $query = $qb->getQuery();

        return $query->getResult();

    }

}
